### ISSUE TITLE
Load relationships from custom queries

### ISSUE THREAD

**Issue by hmy3743** [ash-project/ash_graphql#108]
I try to make custom query that returns type defined in ash graphql

This is my user type
```elixir
defmodule Core.Account.User do
  use Ash.Resource,
    data_layer: AshPostgres.DataLayer,
    extensions: [AshAuthentication, AshGraphql.Resource]

  #...

  relationships do
    has_many :reviews, Core.Review.Review do
      api Core.Review
      destination_attribute :writer_id
    end
  end

  graphql do
    type :user
    hide_fields([:hashed_password])

    queries do
      read_one :user_by_email, :get_by_email
    end
  end
end
```

And this is my review type

```elixir
defmodule Core.Review.Review do
  use Ash.Resource,
    data_layer: AshPostgres.DataLayer,
    extensions: [AshGraphql.Resource]

  #...

  relationships do
    belongs_to :writer, Core.Account.User do
      api Core.Account
      allow_nil? false
    end
  end

  actions do
    defaults [:read]

    create :create do
      primary? true
      argument :writer, Core.Account.User, allow_nil?: false
      change manage_relationship(:writer, type: :append)
    end
  end

  graphql do
    type :review
    queries do
      list :reviews, :read
    end
  end
end
```

And this is my schema
```elixir
defmodule Graphql.Schema do
  use Absinthe.Schema

  @apis [Core.Account, Core.Classification, Core.Review]

  use AshGraphql, apis: @apis

  query do
    field :viewer, type: non_null(:user) do
      resolve(fn _parent, _args, resolution ->
        case resolution.context.actor do
          nil -> {:error, "Not authenticated"}
          actor -> {:ok, actor} # <- |> Core.Account.load!(:reviews)
        end
      end)
    end
  end
end
```

And finally this is my query
```graphql
viewer {
    id
    email
    reviews {
      writer {
        id
      }
      name
    }
  }
  
  userByEmail(email: "email") {
    reviews {
      writer {
        email
      }
    }
  }
```

What happened is
1. When I use custom query `viewer` I can get user's `id`, `email`
2. When I try to get `reviews` from `viewer` query.  I got an error "Cannot return null for non-nullable field" of reviews[0].id
3. When I do `|> Core.Account.load!(:reviews)` before return user in custom query there is no error and I can get `viewer.reviews`
4. But if I try to get `viewer.reviews.writer` I got error again.  it seems like there is no load logic exist when I use custom query
5. If I try `userByEmail` that generated by ash.  I can query nested fields.

Can AshGraphql load relationship fields when query or mutation is custom?

**Comment by zachdaniel** [comment]
So, if you add a custom query like that, you'll need to handle the loading of nested things yourself as well. We have a utility used for subscriptions that you could also use for this, `AshGraphql.Subscription.query_for_subscription(your_ash_query, YourApi, resolution)`.

However, my suggestion would actually be to do the custom action logic in a resource action.

```elixir
read :current_actor do
  manual fn query, _, context -> 
    {:ok, context.actor}
  end
end
```

Then you can hook that up to an `ash_graphql` query :)
