### ISSUE TITLE
Allow giving a description to enum values created with Ash.Type.Enum

### ISSUE THREAD

**Issue by rbino** [ash-project/ash_graphql#116]
AshGraphql is currently missing an ergonomic way to define an enum with some custom descriptions for each value, which are useful for introspection/documentation of the GraphQL schema.

The documentation suggests two possible ways to define a custom enum.

The [first one](https://hexdocs.pm/ash_graphql/use-enums-with-graphql.html#using-ash-enum-types) as far as I know doesn't allow to set a custom description for each value.

The [second one](https://hexdocs.pm/ash_graphql/use-enums-with-graphql.html#using-custom-absinthe-types) basically involves copypasting a piece of the implementation of `Ash.Type.Enum`, and it has the problem that now the values of the enum are listed in two different parts of the application: the Absinthe type and the Ash type.

My thought is that maybe it could be possible to provide a thin wrapper around `Ash.Type.Enum` that also allows to also set the description, something like:

```elixir
defmodule MyEnum do
  use AshGraphql.Type.Enum,
    values: [
      {:foo, "This is a foo"},
      {:bar, "This is a bar"},
      :a_value_with_no_description
    ] 
end
```

If this is feasible and has some value I can try to work on this

**Comment by zachdaniel** [comment]
What we can do is add an optional callback to `AshGraphql.Type` called `describe_enum_value/1` that takes an enum member and returns a description. Then you can do:

```elixir
defmodule MyEnum do
  use Ash.Type.Enum,
    values: [
      :foo,
      :bar,
      :a_value_with_no_description
    ] 

  use AshGraphql.Type

  def describe_enum_value(:foo), do: "...."
end
```

At the same time, I think it would be reasonable to support your proposed tuple format in the core enum type, as enum descriptions could theoretically be used in multiple places. What do you think?

**Comment by rbino** [comment]
Sounds like a plan, I've started working on the Ash side and then I'll circle back here
