### ISSUE TITLE
New pagination default not included in upgrade guide

### ISSUE THREAD

**Issue by rgraff** [ash-project/ash_graphql#129]
In Ash GraphQL 1.0.0-rc.3, For list queries where the resource action has pagination, the graphql query now returns paginated results when previously it didn't.

I actually prefer this, but it is a change that I didn't see in the upgrade guide. I think the new default is :keyset if available.

**Comment by zachdaniel** [comment]
🤔 I'm confused TBH. I thought AshGraphql always does pagination if the action supports it? Was it not doing that before?

I think the thing that changed is that primary actions are now paginatable by default.
