### ISSUE TITLE
An action that `accept`s attributes does not expose those attributes in the schema

### ISSUE THREAD

**Issue by sb8244** [ash-project/ash_graphql#150]
**Describe the bug**

An action that `accept`s attributes does not expose those attributes in the schema unless public? is true

**To Reproduce**

Do not expose public?=true on an attribute, and expose it through accept
```
  attributes do
    uuid_primary_key :id
    attribute :components, {:array, :map}
  end

actions do
    create :create do
      accept [:components]
    end
end
```

**Expected behavior**

The attributes should be visible as arguments

** Runtime
Ash 3.0.0
Ash GraphQL 1.0.0

**Additional context**
Slack reference: https://elixir-lang.slack.com/archives/C0193AHFLPN/p1715449045288019?thread_ts=1715443798.775959&cid=C0193AHFLPN

**Comment by zachdaniel** [comment]
Fixed in 896d76420bc53a70a512640dab1dc4a7906fae75
