### ISSUE TITLE
Feature: Add `intersects` filter for arrays/lists

### ISSUE THREAD

**Issue by frankdugan3** [ash-project/ash_graphql#19]
**Is your feature request related to a problem? Please describe.**
Given the type `attribute(:roles, {:array, :atom}`, it is possible but clunky to use `has` and boolean logic with `or` to filter on where the `roles` field contains any one or more of the items in a given list.

**Describe the solution you'd like**
I would like a filter function akin to `roles intersects items in [opts]` that would handle that logic.

**Express the feature either with a change to resource syntax, or with a change to the resource interface**

For example:

```graphql
filter: { roles: { intersects: [OPTION1, OPTION2, ...] } }
```
Though a traditional intersection usually returns a list of all items that are contained within both lists, in this case it could be lazy and return `true` for the first matching item in both lists since it's a boolean filter rather than a return value.

**Comment by zachdaniel** [comment]
Anyone will be able to add this kind of thing when we do custom operators/functions.
