### ISSUE TITLE
`manual` callback not getting called in the `read_action` of an update mutation

### ISSUE THREAD

**Issue by moxley** [ash-project/ash_graphql#190]
**Describe the bug**

When I define an `update` mutation, with an `identify false` and `read_action action_x`, the `manual` callback defined in `action_x` does not get called.

**To Reproduce**

1. Make the following change to the ash_graphql test suite: https://github.com/moxley/ash_graphql/commit/a98e6ef9def38b9f53a74e39f71423827045f786
2. Run the `AshGraphql.UpdateTest.:"an update with a configured read action and no identity works"/1` test.
3. The `dbg()` statements in `AshGraphql.Test.CurrentActorRead.read()` do not output anything.

**Expected behavior**
One of the `dbg()` statements should output something.

\*\* Runtime

- Elixir version 1.16.1
- Erlang version 26
- OS MacOS
- Ash version 3.0.16
- any related extension versions
  - AshGraphql version 1.2.0

**Additional context**

This might be what is causing [this situation](https://elixirforum.com/t/policy-failure-results-in-raised-unhandled-error-in-ash-graphql-update/64807).

It would be nice if AshGraphql had a more straightforward way to handle the case where a user needs to update their own user record. Am I doing it the recommended way?

Also, I noticed the test still passes with the following expression in the `:best_post` action commented out:

```
# filter(expr(best == true))
```

**Comment by zachdaniel** [comment]
This is actually a bug in ash core, fixed in `3.1.2`. Thank you for the detailed report and helping to identify the issue! 🙇
