### ISSUE TITLE
Add ability to derive sort inputs for related data.

### ISSUE THREAD

**Issue by jimsynz** [ash-project/ash_graphql#215]
**Describe the solution you'd like**

In the example that `Author` has many `Post` I might want to write a query something like this:

```
query {
  authors {
    name
    results {
      posts(sort: [field: "NAME", order: "ASC"]) {
        name
      }
    }
  }
}
```

ie I'd like to be able to sort relationships as they're loaded.

**Describe alternatives you've considered**

We're currently using an action argument that is passed to `Ash.Query.sort_input`.

**Comment by zachdaniel** [comment]
This is already supported :)
