### ISSUE TITLE
"Authorize with GraphQL" guide should include a section about AshAuthentication

### ISSUE THREAD

**Issue by sevenseacat** [ash-project/ash_graphql#245]
This guide 👉 https://hexdocs.pm/ash_graphql/authorize-with-graphql.html

Resolving this issue would help with this: https://github.com/team-alembic/ash_authentication_phoenix/issues/523

**Comment by zachdaniel** [comment]
Addressed in a5da3ea39896be4c949e90b9695596705fa83dc6
