### ISSUE TITLE
Support relay for associations

### ISSUE THREAD

**Issue by zachdaniel** [ash-project/ash_graphql#25]
I've laid the groundwork for relay support, pushed to master now. There are three remaining steps:

* when fetching `:has_many` or `:many_to_many` relationships, we need to wrap them in a connection if the destination action supports pagination

**Comment by zachdaniel** [comment]
Thanks to the amazing work from @dolfinus, we have the core support for relay in place, so all that is left is to make it work for relationships!

**Comment by zachdaniel** [comment]
I've decided that this is out of scope for the moment. The performance of running that many cursors is highly doubtful. For now, instead, you can simply hide those relationships and/or create a calculation that produces a matching type.

**Comment by dolfinus** [comment]
> The performance of running that many cursors is highly doubtful.

What do you mean?

**Comment by zachdaniel** [comment]
Well, its not so much that there would be issues with performance above and beyond the obvious, but if you make one request that has a bunch of related cursors, to seek one cursor you'd need to make the *entire* request again, refetching all cursors. So its a more scalable approach to do that by using a non-nested field for each relationship you want to page through. (i.e use a filter on the `read<associatedResource>` query)

**Comment by dolfinus** [comment]
But the same issue is possible with offset pagination, isn't it?

**Comment by zachdaniel** [comment]
Yeah, but I think people are less likely to use offset pagination on large datasets. I didn't mean to imply that we should *never* add relay for associations, just that I wasn't going to invest more in doing it now because it would be "better" to prefer top-level pagination. If you're interested in working on relay for associations (will have some difficult design considerations, but should be doable) I'm happy to reopen this and we could have that conversation.
