### ISSUE TITLE
Association's calculation not being loaded on mutation

### ISSUE THREAD

**Issue by smt116** [ash-project/ash_graphql#37]
I have a mutation query that in its result loads the record and its `belongs_to` association. The association has a custom calculation attribute that loads a boolean value using an additional db query. Something like:

```graphql
mutation ...($id: ID, $input: ...) {
  ...(id: $id, input: $input) {
    result {
      ...
      user {
        someBooleanFlag
      }
    }
  }
}
```

The API call fails with:

```
 ** (Absinthe.SerializationError) Could not serialize term #Ash.NotLoaded<:calculation> as type Boolean
```

I don't see the additional query in logs so I'm assuming the calculation is not called at all.

**Comment by zachdaniel** [comment]
🤔 very interesting that the association is loaded but not its calculation. Will look into this.

**Comment by zachdaniel** [comment]
So I've pushed up a test that illustrates this behavior working: https://github.com/ash-project/ash_graphql/commit/6b805777aeccfb710dbf6ed4422b31b938af6e83

It would be good to determine what makes those two cases different (and to try out `main` if you haven't already, as the issue may just be fixed in main). It might be useful for me to see the calculation itself.

**Comment by smt116** [comment]
I'm already on the 9bb12460d4408f67d2460b64f4196b698e8c60f7 🤔. I think I've found the root issue. The problem is that my resource (the one that the mutation refers to) is in the "manual" relation with the user (migrating from the legacy system):

```elixir
# relation definition:
    has_one :user, App.Resources.User do
      manual __MODULE__.ManualRelationship.FetchUser
    end

# and the manual relationship:
defmodule App.Resources.SavingHabit.ManualRelationship.FetchUser do
  use Ash.Resource.ManualRelationship

  def load(records, _opts, %{relationship: relationship}) do
    # Return a map of primary keys of the records to the related records.
    # This example is likely suboptimal because it does a separate fetch for
    # each record, whereas you likely want to try to fetch them all at once,
    # and then create the mapping from pkey values to related records
    # For example:

    # get the primary key
    primary_key = Ash.Resource.Info.primary_key(relationship.source)

    {:ok,
     Map.new(records, fn record ->
       pk = Map.get(record, :user_key)
       {:ok, user} = App.Resources.User.get_by_id(pk)
       {Map.take(record, primary_key), user}
     end)}
  end
end
```

I guess it will work just fine after migration relationships from the legacy code (so removing manual in favor of Ash's fk).

**Comment by zachdaniel** [comment]
Ah, well this is definitely a problem. Ash should take care of loading through manual relationships like that. I'll reopen and address, thanks for the report!

**Comment by zachdaniel** [comment]
This is fixed in latest ash main.
