### ISSUE TITLE
(FunctionClauseError) no function clause matching in MyApp.Schema.

### ISSUE THREAD

**Issue by oco-adam** [ash-project/ash_graphql#44]
**Is your feature request related to a problem? Please describe.**

Looks like a bug or the docs could be improved:

Whenever I make a change to anything relating to the Graphql api I'm getting the following error relating to the schema file lib/my_app/schema.ex in VSCode:

```
(FunctionClauseError) no function clause matching in MyApp.Schema."-inlined-__absinthe_function__/2-"/2    
    
    The following arguments were given to MyApp.Schema."-inlined-__absinthe_function__/2-"/2:
    
        # 1
        {Absinthe.Blueprint.Schema.ObjectTypeDefinition, :mutation}
    
        # 2
        :is_type_of
    
    (my_app 0.1.0) MyApp.Schema."-inlined-__absinthe_function__/2-"/2

Stacktrace:
  │ (absinthe 1.7.0) lib/absinthe/phase/schema/inline_functions.ex:40: Absinthe.Phase.Schema.InlineFunctions.inline_function/3
  │ (elixir 1.14.0) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
  │ (absinthe 1.7.0) lib/absinthe/phase/schema/inline_functions.ex:31: Absinthe.Phase.Schema.InlineFunctions.inline_functions/3
  │ (elixir 1.14.0) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
  │ (elixir 1.14.0) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
  │ (absinthe 1.7.0) lib/absinthe/phase/schema/inline_functions.ex:18: Absinthe.Phase.Schema.InlineFunctions.inline_functions/3
  │ (absinthe 1.7.0) lib/absinthe/blueprint/transform.ex:16: anonymous fn/3 in Absinthe.Blueprint.Transform.prewalk/2
```

for example, I just edited the moduledoc for one of the ash APIs included in the GQL schema and it caused the above. These messages go away if I restart VSCode 

**Describe the solution you'd like**
This error seems to go away if the statement

```elixir
  mutation do
  end
```
is added to the Absynth schema.

So if this is the solution then it would be good to add that to the getting started doc.

**Comment by zachdaniel** [comment]
This is now fixed :) You do need to say `query do` and `mutation do` in the schema. Hopefully this is settled because its been a weirdly recurring issue 😆 (my fault, not anyone elses)
