### ISSUE TITLE
Docs error in `managed_relationships`

### ISSUE THREAD

**Issue by dantswain** [ash-project/ash_graphql#48]
Referencing here: https://hexdocs.pm/ash_graphql/AshGraphql.Resource.html#module-managed_relationship

I believe this
```
  managed_relationships do
    managed_relationship :create_post, :comments
  end
```
Should be
```
  managed_relationships do
    managed_relationship :create, :comments
  end
```

While there, I think it might be good to also document the case where we want to use a `Comment` resource to derive a type for the argument rather than a json array.

Also this statement is a bit confusing:
> By default, the {:array, :map} would simply be a json[] type. If the argument name is placed in this list,

I'd be glad to submit one or more PRs to update the docs.  For the last bit, I'd need clarification on what is actually meant by that statement.

**Comment by zachdaniel** [comment]
I've fixed the essential issue of having the wrong atom there, but docs PRs are very welcome to add context or make this easier for users to refer to or understand. Thanks!
