### ISSUE TITLE
No GraphQL fields exposed by AshGraphQL

### ISSUE THREAD

**Issue by moxley** [ash-project/ash_graphql#54]
After following the [Ash Framework tutorial](https://ash-hq.org/docs/guides/ash/2.5.11/tutorials/get-started), then the [AshGraphQL tutorial](https://ash-hq.org/docs/guides/ash_graphql/latest/tutorials/getting-started-with-graphql.md), the resulting GraphQL schema does not contain any of the fields that should have been created from the tutorial.

```
$ curl 'http://localhost:8081/gql' -H 'Content-Type: application/json' --data-raw '{"query":"{ listTickets { id }}"}'
{"errors":[{"locations":[{"column":3,"line":1}],"message":"Cannot query field \"listTickets\" on type \"RootQueryType\"."}]}
```

I double and triple checked my code against the tutorial, but couldn't find any discrepancies.

My app is published to this public GitHub repo: https://github.com/moxley/helpdesk

I must be doing something wrong, because nobody else seems to have run into this issue.

**Comment by moxley** [comment]
I found the problem. It's this part of the tutorial that talks about the module that uses AshApi: https://ash-hq.org/docs/guides/ash_graphql/latest/tutorials/getting-started-with-graphql.md#add-the-api-extension

The example is missing the `resources` DSL call. In my app, that would look like this:

```
defmodule Helpdesk.Api do
  ...

  resources do
    registry Helpdesk.Support.Registry
  end
end
```

Adding the `resources` call as above fixes the issue. The GraphQL fields are now exposed by GraphQL.

**Comment by zachdaniel** [comment]
Hey there, sorry this flew under my radar! I'll take a look at fixing the guide. Thanks for the report!

**Comment by zachdaniel** [comment]
This guide does include configuring the registry: https://ash-hq.org/docs/guides/ash/latest/tutorials/get-started so what I'll do is make sure that 
1. we properly link to the initial getting started guide
2. make a note on each code sample that it should be added to an existing functioning api
3. add a `...` inside of each module that we talk about adding to make it clearer
