### ISSUE TITLE
Error when sorting on aggregate that is not included in query

### ISSUE THREAD

**Issue by ahey** [ash-project/ash_graphql#85]
We have some existing GQL queries that have been successfully sorting on an aggregate, without that aggregate being requested in the response. As of [this ash_postgres commit](https://github.com/ash-project/ash_postgres/commit/0e6bcd047ea3f48280894b1769083a1028bcb238) an error is raised:

```elixir
[error] b401d27c-4794-4c58-9f5c-87bfa716189c: Exception raised while resolving query.

** (KeyError) key :query not found in: %Ash.Resource.Aggregate{
  name: :type_key,
  relationship_path: [:type
```

Adding the aggregate that is being sorted on to the query so it's included in the response resolves the issue.

I am able to reproduce the error directly in the ash_postgres test suite by [commenting out this line](https://github.com/ash-project/ash_postgres/blob/29815eb6ec76c6ee308e83706e8c9da48c1a8194/test/aggregate_test.exs#L325), which produces this:

```elixir
** (KeyError) key :query not found in: 
  %Ash.Resource.Aggregate{
    name: :first_comment,
    relationship_path: [:comments],
    filter: [],
    kind: :first,
    implementation: nil,
    read_action: nil,
    constraints: nil,
    type: nil,
    description: nil,
    private?: false,
    field: :title,
    sort: [title: :asc_nils_last],
    default: nil,
    uniq?: nil,
    authorize?: true,
    filterable?: true
  }
```

It seems like ash_graphql is not loading the aggregate when it's being sorted on but not included in the main query. This seems to be either _as intended_, in which case i will just include the aggregate in the query fields, or it's a bug and ash_graphql should load it automatically.

**Comment by zachdaniel** [comment]
This should be fixed in main, thanks for the report!

**Comment by ahey** [comment]
Thank you, that has resolved my issue! 😄
