### ISSUE TITLE
Ambiguous call to relationships

### ISSUE THREAD

**Issue by rgraff** [ash-project/ash_graphql#86]
The relationships macro inside graphql DSL is ambiguous.

```elixir
  graphql do
    type :environment

    derive_filter?(false)

    queries do
      get :environment, :read, identity: :key
      list(:environments, :read)
    end

    relationships([:accounts])
  end
```

```
== Compilation error in file lib/myapp/organizations/resources/environment.ex ==
** (CompileError) lib/myapp/organizations/resources/environment.ex:36: function relationships/1 imported from both Ash.Resource.Dsl and AshGraphql.Resource.Graphql.Options, call is ambiguous
```

Calling `AshGraphql.Resource.Graphql.Options.relationships` works as expected.

**Comment by zachdaniel** [comment]
What happens if you do `mix deps.update spark` and get spark on the latest?

**Comment by zachdaniel** [comment]
🤔 this doesn't happen for me. What happens if you delete `_build` and recompile?

**Comment by rgraff** [comment]
I recompiled and tried a few other solutions to see if I could get it to work.

Here's my use statement to see everything I'm importing.

```
  use Ash.Resource,
    data_layer: AshPostgres.DataLayer,
    authorizers: [Ash.Policy.Authorizer],
    extensions: [AshGraphql.Resource]
```

**Comment by zachdaniel** [comment]
What elixir/erlang versions are you on? Might be worth updating. The main thing here is that this was a bug we saw in the past but that we made a bunch of fixes to spark to resolve. I've got a resource w/ exactly those extensions that I tried this with and it didn't give me that error :/

**Comment by rgraff** [comment]
I was on 1.14.4, upgrading to 1.15.4 resolved the issued.

**Comment by zachdaniel** [comment]
I just started getting this issue somewhere else! What on earth.

**Comment by zachdaniel** [comment]
Okay, releasing a new version of spark that fixes this :)
