### ISSUE TITLE
Error defining an aggregate of a calculation

### ISSUE THREAD

**Issue by ahey** [ash-project/ash_graphql#93]
A compile time error occurs when defining an aggregate of a calculation. [This PR includes a test that reproduces the issue](https://github.com/ash-project/ash_graphql/pull/92).

**Comment by zachdaniel** [comment]
Fixed in v0.26.0! Thanks for the report and reproduction!

**Comment by ahey** [comment]
Thank you @zachdaniel much appreciated!
