### ISSUE TITLE
UTC timestamps are improperly formatted (bug)

### ISSUE THREAD

**Issue by smt116** [ash-project/ash_graphql#98]
I have an attribute that is `utc_datetime_usec` on the resource side. That resource can be accessed by the GraphQL API consumer. It behaves properly in the iex console:

```elixir
iex([filtered]@localhost)5> [filtered].Broker.get_quote_by_id!("fd941de4-d9f0-4419-8265-1bead97af732", authorize?: false).expires_at
~U[2023-10-30 14:01:10.918342Z]
```

However, the GraphQL result is missing the UTC suffix:

![Zrzut ekranu 2023-10-30 o 15 04 09](https://github.com/ash-project/ash_graphql/assets/619324/495462f9-159b-41f9-9426-a09cfa8f148a)

which breaks frontend code that tries to parse it into a dayjs object.

**Comment by zachdaniel** [comment]
Somehow this fell off my radar, sorry. Ultimately datetime formatting is done by absinthe. I think you are using the backwards compatibility option:

```elixir
config :ash, :utc_datetime_type, :naive_datetime
```

That should be set to `:datetime` which will get you a properly formatted datetime.
